import { Link } from 'expo-router'
import { theme } from '@omi/design-tokens'
import { StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'

import { ScreenHeader } from '../../components/screen-header'
import { useAppTheme } from '../../lib/use-app-theme'

const rows = [['01', 'Sign in', '계정에 로그인하거나 새로 가입합니다.'], ['02', 'Orders', '주문 상태와 배송 흐름을 확인합니다.'], ['03', 'Addresses', '배송지를 추가하고 관리합니다.'], ['04', 'Benefits', '쿠폰, 포인트, 회원 등급을 확인합니다.']]
export default function AccountScreen() { const appTheme = useAppTheme(); return <SafeAreaView edges={['top']} style={[styles.safe, { backgroundColor: appTheme.colors.background }]}><ScreenHeader title="계정" /><View style={styles.wrap}><Text style={[styles.label, { color: appTheme.colors.textMuted }]}>MY OMI</Text><Text style={[styles.title, { color: appTheme.colors.text }]}>나의 OMI.</Text><Text style={[styles.body, { color: appTheme.colors.textMuted }]}>주문과 배송, 혜택을 확인하세요.</Text><Link href="/login" style={[styles.signIn, { backgroundColor: appTheme.colors.accent }]}>로그인</Link><View style={[styles.rows, { borderColor: appTheme.colors.border }]}>{rows.slice(1).map(([no, title, body]) => <View key={no} style={[styles.row, { backgroundColor: appTheme.colors.surface, borderColor: appTheme.colors.border }]}><Text style={[styles.no, { color: appTheme.colors.textMuted }]}>{no}</Text><View><Text style={[styles.rowTitle, { color: appTheme.colors.text }]}>{title}</Text><Text style={[styles.rowBody, { color: appTheme.colors.textMuted }]}>{body}</Text></View><Text style={[styles.arrow, { color: appTheme.colors.textMuted }]}>›</Text></View>)}</View></View></SafeAreaView> }
const styles = StyleSheet.create({ safe: { flex: 1 }, wrap: { padding: 18, paddingTop: 42 }, label: { fontSize: 9, letterSpacing: 1.4 }, title: { fontSize: 48, fontWeight: '700', letterSpacing: -2 }, body: {}, signIn: { marginTop: 28, color: '#fff', borderRadius: 999, overflow: 'hidden', textAlign: 'center', lineHeight: 50, fontWeight: '700' }, rows: { marginTop: 34, gap: 10 }, row: { minHeight: 94, borderWidth: StyleSheet.hairlineWidth, borderRadius: 22, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 16 }, no: { fontSize: 9 }, rowTitle: { fontSize: 21, fontWeight: '700' }, rowBody: { fontSize: 11, marginTop: 3 }, arrow: { marginLeft: 'auto', fontSize: 24 } })
