import { catalogProducts, formatWon } from '@omi/domain'
import { theme } from '@omi/design-tokens'
import { Stack, useLocalSearchParams } from 'expo-router'
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'


export default function ProductScreen() {
  const { productId } = useLocalSearchParams<{ productId: string }>()
  const product = catalogProducts.find((item) => item.productId === productId)
  if (!product) return <SafeAreaView style={styles.missing}><Text>상품을 찾을 수 없습니다.</Text></SafeAreaView>
  return <SafeAreaView edges={['bottom']} style={styles.safe}><Stack.Screen options={{ headerShown: true, title: '', headerTransparent: true, headerTintColor: theme.colors.ink }} /><ScrollView><Image accessibilityLabel={`${product.productName} 전체 이미지`} source={{ uri: product.originImgUrl }} style={styles.image} /><View style={styles.info}><Text style={styles.eyebrow}>{product.tags.join(' · ')}</Text><Text style={styles.title}>{product.productName}</Text><Text style={styles.body}>{product.description}</Text><View style={styles.price}><Text style={styles.priceMain}>{formatWon(product.discountedPrice)}</Text>{product.discountPercent > 0 ? <Text style={styles.discount}>{product.discountPercent}%</Text> : null}</View><View style={styles.facts}><View><Text style={styles.factLabel}>Color</Text><Text>{product.mainColor}</Text></View><View><Text style={styles.factLabel}>Size</Text><Text>{product.size}</Text></View><View><Text style={styles.factLabel}>Stock</Text><Text>{product.soldout ? 'Sold out' : `${product.stock} available`}</Text></View></View><Pressable accessibilityRole="button" disabled={product.soldout} style={[styles.button, product.soldout && styles.disabled]}><Text style={styles.buttonText}>{product.soldout ? 'Sold out' : 'Add to bag'}</Text></Pressable><Pressable accessibilityRole="button" style={styles.save}><Text>♡ Save</Text></Pressable></View></ScrollView></SafeAreaView>
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.paper }, missing: { flex: 1, alignItems: 'center', justifyContent: 'center' }, image: { width: '100%', aspectRatio: .8, resizeMode: 'cover', backgroundColor: '#e5e1d8' }, info: { padding: 22, paddingVertical: 38 }, eyebrow: { fontSize: 9, color: theme.colors.muted, letterSpacing: 1.4 }, title: { fontFamily: 'serif', fontSize: 50, lineHeight: 54, marginTop: 10 }, body: { color: theme.colors.muted, lineHeight: 23, marginTop: 12 }, price: { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: 28 }, priceMain: { fontSize: 18, fontWeight: '700' }, discount: { color: '#8b2f20' }, facts: { borderTopWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.line, marginBottom: 28 }, factLabel: { color: theme.colors.muted, fontSize: 10, marginBottom: 3 }, button: { minHeight: 52, backgroundColor: theme.colors.ink, alignItems: 'center', justifyContent: 'center' }, disabled: { backgroundColor: '#aaa69e' }, buttonText: { color: theme.colors.white, fontWeight: '700' }, save: { minHeight: 52, borderWidth: 1, borderColor: theme.colors.ink, alignItems: 'center', justifyContent: 'center', marginTop: 10 } })
