import { catalogProducts, formatWon } from '@omi/domain'
import { theme } from '@omi/design-tokens'
import { Stack, useLocalSearchParams } from 'expo-router'
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'

import { useMobileCart } from '../../components/mobile-cart-provider'
import { useAppTheme } from '../../lib/use-app-theme'

export default function ProductScreen() {
  const appTheme = useAppTheme()
  const { add } = useMobileCart()
  const { productId } = useLocalSearchParams<{ productId: string }>()
  const product = catalogProducts.find((item) => item.productId === productId)
  if (!product) return <SafeAreaView style={styles.missing}><Text>상품을 찾을 수 없습니다.</Text></SafeAreaView>
  return <SafeAreaView edges={['bottom']} style={[styles.safe, { backgroundColor: appTheme.colors.background }]}><Stack.Screen options={{ headerShown: true, title: '', headerTransparent: true, headerTintColor: appTheme.colors.text }} /><ScrollView><Image accessibilityLabel={`${product.productName} 전체 이미지`} source={{ uri: product.originImgUrl }} style={styles.image} /><View style={styles.info}><Text style={[styles.eyebrow, { color: appTheme.colors.textMuted }]}>{product.tags.join(' · ')}</Text><Text style={[styles.title, { color: appTheme.colors.text }]}>{product.productName}</Text><Text style={[styles.body, { color: appTheme.colors.textMuted }]}>{product.description}</Text><View style={styles.price}><Text style={[styles.priceMain, { color: appTheme.colors.text }]}>{formatWon(product.discountedPrice)}</Text>{product.discountPercent > 0 ? <Text style={[styles.discount, { color: appTheme.colors.danger }]}>{product.discountPercent}%</Text> : null}</View><View style={[styles.facts, { borderColor: appTheme.colors.border }]}><View><Text style={[styles.factLabel, { color: appTheme.colors.textMuted }]}>색상</Text><Text style={{ color: appTheme.colors.text }}>{product.mainColor}</Text></View><View><Text style={[styles.factLabel, { color: appTheme.colors.textMuted }]}>사이즈</Text><Text style={{ color: appTheme.colors.text }}>{product.size}</Text></View><View><Text style={[styles.factLabel, { color: appTheme.colors.textMuted }]}>재고</Text><Text style={{ color: appTheme.colors.text }}>{product.soldout ? '품절' : `${product.stock}개`}</Text></View></View><Pressable accessibilityRole="button" disabled={product.soldout} onPress={() => add(product)} style={[styles.button, { backgroundColor: appTheme.colors.accent }, product.soldout && styles.disabled]}><Text style={styles.buttonText}>{product.soldout ? '품절' : '장바구니에 담기'}</Text></Pressable></View></ScrollView></SafeAreaView>
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.paper }, missing: { flex: 1, alignItems: 'center', justifyContent: 'center' }, image: { width: '100%', aspectRatio: .8, resizeMode: 'cover', backgroundColor: '#e5e1d8' }, info: { padding: 22, paddingVertical: 38 }, eyebrow: { fontSize: 9, color: theme.colors.muted, letterSpacing: 1.4 }, title: { fontFamily: 'serif', fontSize: 50, lineHeight: 54, marginTop: 10 }, body: { color: theme.colors.muted, lineHeight: 23, marginTop: 12 }, price: { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: 28 }, priceMain: { fontSize: 18, fontWeight: '700' }, discount: { color: '#8b2f20' }, facts: { borderTopWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.line, marginBottom: 28 }, factLabel: { color: theme.colors.muted, fontSize: 10, marginBottom: 3 }, button: { minHeight: 52, backgroundColor: theme.colors.ink, alignItems: 'center', justifyContent: 'center' }, disabled: { backgroundColor: '#aaa69e' }, buttonText: { color: theme.colors.white, fontWeight: '700' } })
